project:
  type: website
  output-dir: "."

website:
  title: "Paper Title"
  description: "A research page by IETR-SMILE"
  repo-url: https://ietr-smile.github.io/research-page-template
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: false